import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/index'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/util/authOptions'
import Header from '@/components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Market Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header session={session}/>
        {children}
      </body>
    </html>
  )
}
